Node versions removing * 'avm node rm' command * more informative errors * format ideptation

diff --git a/avm b/avm
--- a/avm
+++ b/avm
@@ -8,7 +8,6 @@ VERSION="0.1.1"
 INIT_PREFIX=${INIT_PREFIX-~/.avm}
 N_PREFIX=${N_PREFIX-/usr/local}
 BASE_VERSIONS_DIR=$INIT_PREFIX/versions
-NODE="node"
 NODE_URL=${NODE_URL-http://adone.io/public/dist/node/}
 NODE_VERSIONS_DIR=$BASE_VERSIONS_DIR/node
 
@@ -17,11 +16,19 @@ log() {
 }
 
 error() {
-    printf "\n  \033[31mError: $@\033[0m\n"
+  printf "\n  \033[31mError: $@\033[0m\n\n"
+}
+
+warning() {
+  printf "\n  \033[33mWarning: $@\033[0m\n\n"
 }
 
 abort() {
   error "$@" && printf "\n" && exit 1
+}
+
+notsupported() {
+  abort "not supported yet"
 }
 
 #
@@ -44,9 +51,10 @@ test -z "$GET" && abort "curl or wget required"
 
 QUIET=false
 DOWNLOAD=false
+REMOVE_ACTIVE=false
 ARCH=
 
-test -d ${NODE_VERSIONS_DIR} || mkdir -p ${NODE_VERSIONS_DIR}
+test -d ${BASE_VERSIONS_DIR} || mkdir -p ${BASE_VERSIONS_DIR}
 
 #
 # set_arch <arch> to override $(uname -a)
@@ -56,7 +64,7 @@ set_arch() {
   if test ! -z $1; then
     ARCH=$1
   else
-    abort "missing -a|--arch value"
+    abort_help "missing -a|--arch value"
   fi
 }
 
@@ -71,21 +79,21 @@ display_help() {
 
   Commands:
 
-    avm                              Output local available versions
-    avm install                      Install avm global
-    avm uninstall                    Uninstall global installed avm
-    avm update                       Update global installed avm
-    avm list                         Output available adone versions
+    avm                               Output local available versions
+    avm install                       Install avm global
+    avm uninstall                     Uninstall global installed avm
+    avm update                        Update global installed avm
+    avm list                          Output available adone versions
     avm [--download] [--sources] <version>
-                                     Install adone <version>. <version> can be 'latest'
-    avm rm [--active] <version ...>  Remove the given adone version(s)
-    avm node list                    Output available node versions
+                                      Install adone <version>. <version> can be 'latest'
+    avm rm [--active] <version ...>   Remove the given adone version(s)
+    avm node list                     Output available node versions
     avm node [--download] [--sources] <version>
-                                     Install node <version>. <version> can be 'latest'
-    avm node [--active] rm <version ...>
-                                     Remove the given node version(s)
-    avm backup                       Backup current adone version
-    avm [--complete] clear           Delete all downloaded
+                                      Install node <version>. <version> can be 'latest'
+    avm node rm [--active] <version ...>
+                                      Remove the given node version(s)
+    avm backup                        Backup current adone version
+    avm [--complete] clear            Delete all downloaded
 
   Options:
 
@@ -101,8 +109,9 @@ display_help() {
 EOF
 }
 
-err_no_installed_print_help() {
-  error "no installed version"
+abort_help() {
+  error "$@"
+  erase_line
   display_help
   exit 1
 }
@@ -112,30 +121,14 @@ display_version() {
 }
 
 #
-# Check for installed version, and populate $active
-#
-
-check_current_node_version() {
-  if which node > /dev/null; then
-    local current=$(node --version)
-    current=${current#v}
-    if cmp -s \
-      $BASE_VERSIONS_DIR/$NODE/$current/bin/node \
-      `which node` ; then
-      active=$NODE/$current
-    fi
-  fi
-}
-
-#
 # Display sorted versions directories paths.
 #
 
 versions_paths() {
   find $BASE_VERSIONS_DIR -maxdepth 2 -type d \
-    | sed 's|'$BASE_VERSIONS_DIR'/||g' \
-    | egrep "/[0-9]+\.[0-9]+\.[0-9]+$" \
-    | sort -k 1,1 -k 2,2n -k 3,3n -t .
+  | sed 's|'$BASE_VERSIONS_DIR'/||g' \
+  | egrep "/[0-9]+\.[0-9]+\.[0-9]+$" \
+  | sort -k 1,1 -k 2,2n -k 3,3n -t .
 }
 
 #
@@ -163,15 +156,6 @@ list_versions_installed() {
   for version in $(versions_paths); do
     echo $version
   done
-}
-
-#
-# Display current node --version and others installed.
-#
-
-display_versions() {
-  check_current_node_version
-  display_versions_with_selected $active
 }
 
 #
@@ -213,42 +197,6 @@ is_oss_ok() {
 }
 
 #
-# Determine tarball url for <version>
-#
-
-tarball_url() {
-  local version=$1
-  local uname="$(uname -a)"
-  local arch=x86
-  local os=
-
-  # from nave(1)
-  case "$uname" in
-    Linux*) os=linux ;;
-    Darwin*) os=darwin ;;
-    SunOS*) os=sunos ;;
-  esac
-
-  case "$uname" in
-    *x86_64*) arch=x64 ;;
-    *armv6l*) arch=armv6l ;;
-    *armv7l*) arch=armv7l ;;
-  esac
-
-  if test "$arch" = "armv6l" && test "$NODE" = node; then
-    local semver=${version//./ }
-    local major=$(echo $semver | grep -o -E '[0-9]+' | head -1 | sed -e 's/^0\+//')
-    local minor=$(echo $semver | awk '{print $2}' | grep -o -E '[0-9]+' | head -1 | sed -e 's/^0\+//')
-    test $major -eq "" && test $minor -lt 12 && arch=arm-pi
-  fi
-
-  test -n "$ARCH" && arch=$ARCH
-
-  echo "${NODE_URL}${version}/${os}-${arch}.tar.gz"
-
-}
-
-#
 # Disable PaX mprotect for <binary>
 #
 
@@ -274,23 +222,11 @@ disable_pax_mprotect() {
 }
 
 #
-# Activate node <version>
+# Set curl to quiet (silent) mode.
 #
 
-activate() {
-  local version=$1
-  check_current_node_version
-  if test "$version" != "$active"; then
-    local dir=$BASE_VERSIONS_DIR/$version
-    for subdir in bin lib include share; do
-      if test -L "$N_PREFIX/$subdir"; then
-        find "$dir/$subdir" -mindepth 1 -maxdepth 1 -exec cp -fR "{}" "$N_PREFIX/$subdir" \;
-      else
-        cp -fR "$dir/$subdir" $N_PREFIX
-      fi
-    done
-    disable_pax_mprotect "$N_PREFIX/bin/node"
-  fi
+set_quiet() {
+  which curl > /dev/null && GET="$GET -s" && QUIET=true
 }
 
 #
@@ -302,11 +238,96 @@ check_root() {
 }
 
 #
+# Check for installed node version, and populate $active
+#
+
+check_current_node_version() {
+  if which node > /dev/null; then
+    local current=$(node --version)
+    current=${current#v}
+    if cmp -s \
+    $BASE_VERSIONS_DIR/node/$current/bin/node \
+    `which node` ; then
+      active=$current
+    fi
+  fi
+}
+
+#
+# Display current node --version and others installed.
+#
+
+display_versions() {
+  check_current_node_version
+  display_versions_with_selected $active
+}
+
+#
+# Determine node tarball url for <version>
+#
+
+node_tarball_url() {
+  local version=$1
+  local uname="$(uname -a)"
+  local arch=x86
+  local os=
+
+  case "$uname" in
+    Linux*) os=linux ;;
+    Darwin*) os=darwin ;;
+    SunOS*) os=sunos ;;
+  esac
+
+  case "$uname" in
+    *x86_64*) arch=x64 ;;
+    *armv6l*) arch=armv6l ;;
+    *armv7l*) arch=armv7l ;;
+  esac
+
+  if test "$arch" = "armv6l"; then
+    local semver=${version//./ }
+    local major=$(echo $semver | grep -o -E '[0-9]+' | head -1 | sed -e 's/^0\+//')
+    local minor=$(echo $semver | awk '{print $2}' | grep -o -E '[0-9]+' | head -1 | sed -e 's/^0\+//')
+    test $major -eq "" && test $minor -lt 12 && arch=arm-pi
+  fi
+
+  test -n "$ARCH" && arch=$ARCH
+
+  echo "${NODE_URL}${version}/${os}-${arch}.tar.gz"
+
+}
+
+#
+# Activate node <version>
+#
+
+activate_node() {
+  local version=$1
+  check_current_node_version
+  if test "$version" != "$active"; then
+    local dir=$NODE_VERSIONS_DIR/$version
+    for subdir in bin lib include share; do
+      if test -L "$N_PREFIX/$subdir"; then
+        find "$dir/$subdir" -mindepth 1 -maxdepth 1 -exec cp -fR "{}" "$N_PREFIX/$subdir" \;
+      else
+        cp -fR "$dir/$subdir" $N_PREFIX
+      fi
+    done
+    disable_pax_mprotect "$N_PREFIX/bin/node"
+    log activated node-v$version
+  else
+    warning "Node $version is already active"
+  fi
+}
+
+#
 # Install node <version>
 #
 
 install_node() {
   check_root || abort "root access required"
+
+  test -d ${NODE_VERSIONS_DIR} || mkdir -p ${NODE_VERSIONS_DIR}
 
   local version=${1#v}
 
@@ -321,7 +342,7 @@ install_node() {
       | egrep ^$version \
       | tail -n1)
 
-    test $version || abort "invalid version ${1#v}"
+    test $version || abort_help "invalid version ${1#v}"
   fi
 
   local dir=${NODE_VERSIONS_DIR}/$version
@@ -329,16 +350,16 @@ install_node() {
   if test -d $dir; then
     if test ! -e $dir/n.lock; then
       if test $DOWNLOAD = false ; then
-        activate ${NODE}/$version
+        activate_node $version
       fi
       exit
     fi
   fi
 
   echo
-  log install ${NODE}-v$version
+  log install node-v$version
 
-  local url=$(tarball_url $version)
+  local url=$(node_tarball_url $version)
   is_ok $url || is_oss_ok $url || abort "cannot fetch version $version"
 
   log mkdir $dir
@@ -359,31 +380,52 @@ install_node() {
   disable_pax_mprotect bin/node
 
   if test $DOWNLOAD = false ; then
-    activate ${NODE}/$version
-    log installed $(node --version)
+    activate_node $version
+    log installed node-$(node --version)
   fi
   echo
 }
 
 #
-# Set curl to quiet (silent) mode.
+# Remove active node
 #
 
-set_quiet() {
-  which curl > /dev/null && GET="$GET -s" && QUIET=true
+remove_node_active() {
+  check_root || abort "root access required"
+
+  for f in `find ${NODE_VERSIONS_DIR}/$active -mindepth 2 ! -type d | sort -r`; do
+    rm "$N_PREFIX${f#${NODE_VERSIONS_DIR}/$active}"
+  done
+
+  for d in `find ${NODE_VERSIONS_DIR}/$active -mindepth 2 -type d | sort -r`; do
+    rmdir "$N_PREFIX${d#${NODE_VERSIONS_DIR}/$active}" > /dev/null
+  done
 }
 
 #
-# Remove <version ...>
+# Remove node <version ...>
 #
 
-remove_versions() {
-  test -z $1 && abort "version(s) required"
+remove_node_versions() {
+  if test $1 = "--active"; then
+    REMOVE_ACTIVE=true
+    shift
+  fi
+
+  test -z $1 && abort_help "version(s) required"
   check_current_node_version
   while test $# -ne 0; do
     local version=${1#v}
-    test "${NODE}/$version" = "$active" && abort "cannot remove currently active version ($active)"
+    test -d ${NODE_VERSIONS_DIR}/$version || abort_help "Node version $version is not installed"
+    if test "$version" = "$active"; then
+      if test $REMOVE_ACTIVE = true; then
+        remove_node_active
+      else
+        abort_help "Cannot remove currently active version ($active).\n         Specify --active option to force removing."
+      fi
+    fi
     rm -rf ${NODE_VERSIONS_DIR}/$version
+    log removed $version
     shift
   done
 }
@@ -409,12 +451,12 @@ display_bin_path_for_version() {
 
 display_latest_version() {
   $GET 2> /dev/null ${NODE_URL} \
-    | egrep "</a>" \
-    | egrep -o '[0-9]+\.[0-9]+\.[0-9]+' \
-    | egrep -v '^0\.[0-7]\.' \
-    | egrep -v '^0\.8\.[0-5]$' \
-    | sort -u -k 1,1n -k 2,2n -k 3,3n -t . \
-    | tail -n1
+  | egrep "</a>" \
+  | egrep -o '[0-9]+\.[0-9]+\.[0-9]+' \
+  | egrep -v '^0\.[0-7]\.' \
+  | egrep -v '^0\.8\.[0-5]$' \
+  | sort -u -k 1,1n -k 2,2n -k 3,3n -t . \
+  | tail -n1
 }
 
 #
@@ -423,10 +465,10 @@ display_latest_version() {
 
 display_latest_stable_version() {
   $GET 2> /dev/null ${NODE_URL} \
-    | egrep "</a>" \
-    | egrep -o '[0-9]+\.[0-9]*[02468]\.[0-9]+' \
-    | sort -u -k 1,1n -k 2,2n -k 3,3n -t . \
-    | tail -n1
+  | egrep "</a>" \
+  | egrep -o '[0-9]+\.[0-9]*[02468]\.[0-9]+' \
+  | sort -u -k 1,1n -k 2,2n -k 3,3n -t . \
+  | tail -n1
 }
 
 #
@@ -438,12 +480,12 @@ display_latest_lts_version() {
     | egrep "</a>" \
     | egrep -o 'latest-[a-z]{2,}' \
     | sort \
-    | tail -n1)
+  | tail -n1)
 
   $GET 2> /dev/null ${NODE_URL}/$folder_name/ \
-    | egrep "</a>" \
-    | egrep -o '[0-9]+\.[0-9]+\.[0-9]+' \
-    | head -n1
+  | egrep "</a>" \
+  | egrep -o '[0-9]+\.[0-9]+\.[0-9]+' \
+  | head -n1
 }
 
 #
@@ -457,7 +499,7 @@ display_remote_versions() {
     | egrep "href" \
     | egrep -o '[0-9]+\.[0-9]+\.[0-9]+' \
     | sort -u -k 1,1n -k 2,2n -k 3,3n -t . \
-    | awk '{ print "  " $1 }')
+  | awk '{ print "  " $1 }')
 
   echo
   local bin=${NODE}
@@ -480,26 +522,26 @@ display_remote_versions() {
 #
 
 node_command() {
-    if test $# -eq 0; then
-      test -z "$(versions_paths)" && err_no_installed_print_help
-      display_versions
-    else
-        while test $# -ne 0; do
-          case $1 in
-            --latest) display_latest_version; exit ;;
-            --stable) display_latest_stable_version; exit ;;
-            --lts) display_latest_lts_version; exit ;;
-            bin) display_bin_path_for_version $2; exit ;;
-            rm) shift; remove_versions $@; exit ;;
-            latest) install_node $(display_latest_version); exit ;;
-            stable) install_node $(display_latest_stable_version); exit ;;
-            lts) install_node $(display_latest_lts_version); exit ;;
-            list) display_remote_versions; exit ;;
-            *) install_node $1; exit ;;
-          esac
-          shift
-        done
-    fi
+  if test $# -eq 0; then
+    test -z "$(versions_paths)" && abort_help "no installed versions"
+    display_versions
+  else
+    while test $# -ne 0; do
+      case $1 in
+        --latest) display_latest_version; exit ;;
+        --stable) display_latest_stable_version; exit ;;
+        --lts) display_latest_lts_version; exit ;;
+        bin) display_bin_path_for_version $2; exit ;;
+        rm) shift; remove_node_versions $@; exit ;;
+        latest) install_node $(display_latest_version); exit ;;
+        stable) install_node $(display_latest_stable_version); exit ;;
+        lts) install_node $(display_latest_lts_version); exit ;;
+        list) display_remote_versions; exit ;;
+        *) install_node $1; exit ;;
+      esac
+      shift
+    done
+  fi
 }
 
 #
@@ -507,21 +549,18 @@ node_command() {
 #
 
 if test $# -eq 0; then
-  test -z "$(versions_paths)" && err_no_installed_print_help
+  test -z "$(versions_paths)" && abort_help "no installed versions"
   display_versions
 else
   while test $# -ne 0; do
     case $1 in
-      -V|--version) display_version ;;
+      -V|--version) display_version exit ;;
       -h|--help|help) display_help; exit ;;
       -q|--quiet) set_quiet ;;
       -d|--download) DOWNLOAD=true ;;
-      --latest) display_latest_version; exit ;;
-      --stable) display_latest_stable_version; exit ;;
-      --lts) display_latest_lts_version; exit ;;
-      -a|--arch) shift; set_arch $1;; # set arch and continue
+      -a|--arch) shift; set_arch $1;;
       node) shift; node_command $@; exit ;;
-      *) abort "not supported yet"; exit ;;
+      *) notsupported; exit ;;
     esac
     shift
   done
